app:
  file:
    allowed-types: image/jpeg,image/png,image/webp
    max-size: 5242880
jwt:
  expiration: 86400000
aws:
  s3:
    region: us-east-1
spring:
  config:
    import: optional:secrets.yml
  application:
    name: movies
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      max-file_size: 5MB
      max-request-size: 5MB
  flyway:
    baseline-on-migrate: true
    repair-on-migrate: true
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: false
